services: docker

env:
    MODULE=tim22

language: python

python:
  - "3.7"

install:
  - docker-compose --file docker/docker-compose.dev.yml up --no-start --remove-orphans tim22_test
  - docker-compose --file docker/docker-compose.dev.yml up --no-start --remove-orphans dbmarket

script:
  - docker-compose --file docker/docker-compose.dev.yml run tim22_test
